/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.IOException;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;

/**
 *
 * @author hcorrea
 */
public class Production extends javax.swing.JFrame {

    /**
     * Creates new form Production
     */
 ;

    public Production() throws IOException, ClassNotFoundException {
        initComponents();
//        jdpEscritorio.setBorder(new Background());
        this.setExtendedState(Production.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jdpEscritorio = new javax.swing.JDesktopPane();
        jmbMenu = new javax.swing.JMenuBar();
        jmnuInicio = new javax.swing.JMenu();
        jmnuTablas = new javax.swing.JMenu();
        jmiEstatusMaquina = new javax.swing.JMenuItem();
        jmiFallosMaquina = new javax.swing.JMenuItem();
        jmiAtributos = new javax.swing.JMenuItem();
        jmiGastosFabrica = new javax.swing.JMenuItem();
        jmiMaquinas = new javax.swing.JMenuItem();
        jmnuProcesos = new javax.swing.JMenu();
        jmiOrdenProducto = new javax.swing.JMenuItem();
        jmiTareas = new javax.swing.JMenuItem();
        jmnuReportes = new javax.swing.JMenu();
        jmnuInventario = new javax.swing.JMenu();
        jmiArticulos = new javax.swing.JMenuItem();
        jmiCedulaProducto = new javax.swing.JMenuItem();
        jmnuAdministracion = new javax.swing.JMenu();
        jmiPerfilEmpleado = new javax.swing.JMenuItem();
        jmnuMantenimiento = new javax.swing.JMenu();
        jmnuEmpresas = new javax.swing.JMenu();
        jmnuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Production - MIT");

        jdpEscritorio.setToolTipText("");
        jdpEscritorio.setAutoscrolls(true);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        jmbMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jmnuInicio.setText("Inicio");
        jmbMenu.add(jmnuInicio);

        jmnuTablas.setText("Tablas");

        jmiEstatusMaquina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Produccion.png"))); // NOI18N
        jmiEstatusMaquina.setText("Estatus de Maquina");
        jmnuTablas.add(jmiEstatusMaquina);

        jmiFallosMaquina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FallasMaquinas.png"))); // NOI18N
        jmiFallosMaquina.setText("Fallos de Maquina");
        jmnuTablas.add(jmiFallosMaquina);

        jmiAtributos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Atributos.png"))); // NOI18N
        jmiAtributos.setText("Atributos");
        jmnuTablas.add(jmiAtributos);

        jmiGastosFabrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gastosdefabrica.png"))); // NOI18N
        jmiGastosFabrica.setText("Gastos de Fabrica");
        jmnuTablas.add(jmiGastosFabrica);

        jmiMaquinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Maquinas.png"))); // NOI18N
        jmiMaquinas.setText("Maquinas");
        jmnuTablas.add(jmiMaquinas);

        jmbMenu.add(jmnuTablas);

        jmnuProcesos.setText("Procesos");

        jmiOrdenProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tareas.png"))); // NOI18N
        jmiOrdenProducto.setText("Orden de Producto");
        jmnuProcesos.add(jmiOrdenProducto);

        jmiTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tareas.png"))); // NOI18N
        jmiTareas.setText("Tareas");
        jmnuProcesos.add(jmiTareas);

        jmbMenu.add(jmnuProcesos);

        jmnuReportes.setText("Reportes");
        jmbMenu.add(jmnuReportes);

        jmnuInventario.setText("Inventario");

        jmiArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventario.png"))); // NOI18N
        jmiArticulos.setText("Articulos");
        jmnuInventario.add(jmiArticulos);

        jmiCedulaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CedProducto.png"))); // NOI18N
        jmiCedulaProducto.setText("Cedula de Producto");
        jmnuInventario.add(jmiCedulaProducto);

        jmbMenu.add(jmnuInventario);

        jmnuAdministracion.setText("Administracion");

        jmiPerfilEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PerfilesEmpleados.png"))); // NOI18N
        jmiPerfilEmpleado.setText("Perfil de Empleado");
        jmnuAdministracion.add(jmiPerfilEmpleado);

        jmbMenu.add(jmnuAdministracion);

        jmnuMantenimiento.setText("Mantenimiento");
        jmbMenu.add(jmnuMantenimiento);

        jmnuEmpresas.setText("Empresas");
        jmbMenu.add(jmnuEmpresas);

        jmnuAyuda.setText("Ayuda");
        jmbMenu.add(jmnuAyuda);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return 
     */

    public JMenuItem getJmiArticulos() {
        return jmiArticulos;
    }

    public void setJmiArticulos(JMenuItem jmiArticulos) {
        this.jmiArticulos = jmiArticulos;
    }

    public JMenuItem getJmiAtributos() {
        return jmiAtributos;
    }

    public void setJmiAtributos(JMenuItem jmiAtributos) {
        this.jmiAtributos = jmiAtributos;
    }

    public JMenuItem getJmiCedulaProducto() {
        return jmiCedulaProducto;
    }

    public void setJmiCedulaProducto(JMenuItem jmiCedulaProducto) {
        this.jmiCedulaProducto = jmiCedulaProducto;
    }

    public JMenuItem getJmiEstatusMaquina() {
        return jmiEstatusMaquina;
    }

    public void setJmiEstatusMaquina(JMenuItem jmiEstatusMaquina) {
        this.jmiEstatusMaquina = jmiEstatusMaquina;
    }

    public JMenuItem getJmiFallosMaquina() {
        return jmiFallosMaquina;
    }

    public void setJmiFallosMaquina(JMenuItem jmiFallosMaquina) {
        this.jmiFallosMaquina = jmiFallosMaquina;
    }

    public JMenuItem getJmiGastosFabrica() {
        return jmiGastosFabrica;
    }

    public void setJmiGastosFabrica(JMenuItem jmiGastosFabrica) {
        this.jmiGastosFabrica = jmiGastosFabrica;
    }

    public JMenuItem getJmiMaquinas() {
        return jmiMaquinas;
    }

    public void setJmiMaquinas(JMenuItem jmiMaquinas) {
        this.jmiMaquinas = jmiMaquinas;
    }

    public JMenuItem getJmiOrdenProducto() {
        return jmiOrdenProducto;
    }

    public void setJmiOrdenProducto(JMenuItem jmiOrdenProducto) {
        this.jmiOrdenProducto = jmiOrdenProducto;
    }

    public JMenuItem getJmiPerfilEmpleado() {
        return jmiPerfilEmpleado;
    }

    public void setJmiPerfilEmpleado(JMenuItem jmiPerfilEmpleado) {
        this.jmiPerfilEmpleado = jmiPerfilEmpleado;
    }

    public JMenuItem getJmiTareas() {
        return jmiTareas;
    }

    public void setJmiTareas(JMenuItem jmiTareas) {
        this.jmiTareas = jmiTareas;
    }

    public static JDesktopPane getJdpEscritorio() {
        return jdpEscritorio;
    }

    public static void setJdpEscritorio(JDesktopPane jdpEscritorio) {
        Production.jdpEscritorio = jdpEscritorio;
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiArticulos;
    private javax.swing.JMenuItem jmiAtributos;
    private javax.swing.JMenuItem jmiCedulaProducto;
    private javax.swing.JMenuItem jmiEstatusMaquina;
    private javax.swing.JMenuItem jmiFallosMaquina;
    private javax.swing.JMenuItem jmiGastosFabrica;
    private javax.swing.JMenuItem jmiMaquinas;
    private javax.swing.JMenuItem jmiOrdenProducto;
    private javax.swing.JMenuItem jmiPerfilEmpleado;
    private javax.swing.JMenuItem jmiTareas;
    private javax.swing.JMenu jmnuAdministracion;
    private javax.swing.JMenu jmnuAyuda;
    private javax.swing.JMenu jmnuEmpresas;
    private javax.swing.JMenu jmnuInicio;
    private javax.swing.JMenu jmnuInventario;
    private javax.swing.JMenu jmnuMantenimiento;
    private javax.swing.JMenu jmnuProcesos;
    private javax.swing.JMenu jmnuReportes;
    private javax.swing.JMenu jmnuTablas;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
